"""New migration message

Revision ID: cef062501268
Revises: f3ede0e5ff59
Create Date: 2025-01-13 13:54:07.570382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cef062501268'
down_revision: Union[str, None] = 'f3ede0e5ff59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trial')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('get', sa.VARCHAR(), nullable=False),
    sa.Column('fr', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
